AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRC Website ACM Cert. and CloudFront Distro.'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: warnerbell.com
      SubjectAlternativeNames: 
        - "*.warnerbell.com"
      DomainValidationOptions:
        - DomainName: warnerbell.com
          HostedZoneId: Z0507821205XVUTOQ9OO2
      ValidationMethod: DNS

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Static Site 

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - warnerbell.com
          - www.warnerbell.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: s3Origin
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: warnerbell.com
            Id: s3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: "warnerbell.com"
      RecordSets:
      - Name: "warnerbell.com"
        Type: A
        AliasTarget:
          DNSName:
            Fn::GetAtt:
            - Distribution
            - DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z0507821205XVUTOQ9OO2
      - Name: "www.warnerbell.com"
        Type: A
        AliasTarget:
          DNSName:
            Fn::GetAtt:
            - Distribution
            - DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z0507821205XVUTOQ9OO2
  
Outputs:
  CertificateArn:
    Description: Issued certificate
    Value:
      Ref: Certificate
  CloudFrontDistribution:
    Description: CloudFront distribution
    Value:
      Fn::GetAtt:
      - Distribution
      - DomainName
  
