AWSTemplateFormatVersion: '2010-09-09'
Description: 'CRC Website ACM Cert. and CloudFront Distro.'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: warnerbell.com
      SubjectAlternativeNames: 
        - "warnerbell.com"
        - "www.warnerbell.com"
      DomainValidationOptions:
        - DomainName: warnerbell.com
          HostedZoneId: Z0507821205XVUTOQ9OO2
        - DomainName: www.warnerbell.com
          HostedZoneId: Z0507821205XVUTOQ9OO2
      ValidationMethod: DNS

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Static Site 

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - warnerbell.com
          - www.warnerbell.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: warnerbell.com.s3.us-east-1.amazonaws.com
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: warnerbell.com
            Id: warnerbell.com.s3.us-east-1.amazonaws.com
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: "warnerbell.com."
      RecordSets:
      - Name: "warnerbell.com"
        Type: A
        AliasTarget:
          DNSName:
            Fn::GetAtt:
            - Distribution
            - DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
      - Name: "www.warnerbell.com"
        Type: A
        AliasTarget:
          DNSName:
            Fn::GetAtt:
            - Distribution
            - DomainName
          EvaluateTargetHealth: false
          HostedZoneId: Z2FDTNDATAQYW2
    DependsOn: 
      - Distribution
  
Outputs:
  CertificateArn:
    Description: Issued certificate
    Value:
      Ref: Certificate
  CloudFrontDistribution:
    Description: CloudFront distribution
    Value:
      Fn::GetAtt:
      - Distribution
      - DomainName
  CloudFrontOriginAccessIdentity:
    Description: CloudFront origin access identity ID
    Value:
      !Ref CloudFrontOriginAccessIdentity
  
