AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Cloud Resume Challenge website S3 bucket.'
Resources:

  S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: coming-soon.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    #DeletionPolicy: Retain

  S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: www.coming-soon.com
    #DeletionPolicy: Retain

  S3Bucket3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: logs.coming-soon.com
    #DeletionPolicy: Retain
    
Outputs:
  WebsiteURL:
    Value:
      Fn::GetAtt:
      - S3Bucket1
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
