AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Cloud Resume Challenge website S3 bucket.'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: warnerbell.com
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    
Outputs:
  WebsiteURL:
    Value:
      Fn::GetAtt:
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Fn::GetAtt:
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
