name: Deploy Site
on: 
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Site
        run: bash ./bin/website-deploy