name: Destroy Site

on: 
  workflow_dispatch

jobs:
  SiteKill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

        env:
          AWS_REGION: 'us-east-1'

      - name: Tear Down Site
        run: bash ./bin/website-destroy