name: Deploy Site

on: 
  workflow_dispatch
  
jobs:
  SiteBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build Site
        run: |
          chmod u+x ./bin/website-deploy
          sleep 5s
          ./bin/website-deploy
        env:
          AWS_REGION: 'us-east-1'