name: Destroy Site

on: 
  workflow_dispatch

jobs:
  SiteKill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Tear Down Site
        run: |
          chmod u+x ./bin/website-destroy
          sleep 5s
          ./bin/website-destroy
        env:
          AWS_REGION: 'us-east-1'